name: Deploy Selected Snapshot Modules

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday at 00:00 UTC

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_TOKEN: ${{ secrets.MAVEN_TOKEN }}
      GITHUB_ACTOR: ${{ secrets.MAVEN_USER }}
    
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Deploy parent
        run: mvn clean deploy -N

      - name: Deploy selected snapshot modules
        run: mvn clean deploy -pl "dynameq,emulation,greedo,roundtrips,samgods,utils,atap" -am
